### ISSUE TITLE
使用 wlc.NewTest 會出現 1008-SYS REQ PARTNER ERROR

### ISSUE THREAD

**Issue by ITyouG** [smartwalle/wlc#2]
如標題所說，填上自己的appId, secretKey, bizId後，執行 wlc.NewTes 會出現下面的錯誤

实名认证发生错误: 1008-SYS REQ PARTNER ERROR
实名认证发生错误: 1008-SYS REQ PARTNER ERROR
实名认证发生错误: 1008-SYS REQ PARTNER ERROR
实名认证查询发生错误: 1008-SYS REQ PARTNER ERROR
实名认证查询发生错误: 1008-SYS REQ PARTNER ERROR
实名认证查询发生错误: 1008-SYS REQ PARTNER ERROR
上报数据发生错误: 1008-SYS REQ PARTNER ERROR
上报数据发生错误: 1008-SYS REQ PARTNER ERROR

**Comment by smartwalle** [comment]
网络游戏防沉迷实名认证系统->数据共享->接口测试   里面的参数
