### ISSUE TITLE
希望支持可选的 *http.Client

### ISSUE THREAD

**Issue by wangzhongkuo** [smartwalle/wlc#3]
New(appId, secretKey, bizId string) Client 时希望可以设置内部的 *http.Client。因为很多时候我们会调整 *http.Client，或者对 *http.Client 进行一些封装。希望作者可以提供一个可选参数用于设置 *http.Client。

**Comment by smartwalle** [comment]
这个可以有，晚些时间我处理一下

**Comment by smartwalle** [comment]
新版本已经提交，有用就点个小星星吧。

**Comment by wangzhongkuo** [comment]
非常感谢，start 已点，祝您好运。
