### ISSUE TITLE
是否可以支持传入 context，用来做链路追踪和程序中断

### ISSUE THREAD

**Issue by whrss9527** [smartwalle/wlc#4]
在使用自定义的 http client 时，无法传入 context，链路追踪无法监测 http 请求。能否在调用时支持传入 context，在使用 http request 时使用 http.NewRequestWithContext 替换 http.NewRequest 来实现～

**Comment by whrss9527** [comment]
https://github.com/smartwalle/wlc/pull/5
我提交了一个 pr，麻烦您看下可以不～

**Comment by smartwalle** [comment]
已合并
